version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    networks:
      - team-sarp-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - team-sarp-network

networks:
  team-sarp-network:
    driver: bridge